import { createElement } from '@lwc/engine-dom';
import Lwccomponentfirst_19_25 from 'c/lwccomponentfirst_19_25';

describe('c-lwccomponentfirst-19-25', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwccomponentfirst-19-25', {
            is: Lwccomponentfirst_19_25
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});